#!/bin/sh


instance_name=$1

usage="deploy-nifi-lib <instance_name>"
if [ -z $instance_name ]
then
  echo $usage
  exit 1
fi

rsync -avzh \
  -e "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
  $NIFI_SS_HOME/lib/ ec2-user@${instance_name}.aws.mine:/opt/nifi/lib

