#!/bin/sh

for service_name in `cat security-groups |awk '{print $1}'`
do
  i=0
  for public_ip in `./query-public-ips ${service_name}`
  do
    echo "${public_ip}\t${i}.${service_name}.aws.mine"
    i=`expr $i + 1`
  done
done
