#!/bin/sh

service_name=$1

usage="query-public-dns-names <service_name>"

if [ -z $service_name ]
then
  echo $usage
  exit 1
fi

for i in `./query-instance-id-by-sg ${service_name}`
do
  aws ec2 describe-instances --region us-west-1 --instance-ids $i \
    |jq -r ".Reservations[].Instances[].NetworkInterfaces[].Association.PublicDnsName"
done

