#!/bin/sh

instance_name=$1
remote_file=$2
local_file=$3

if [ -z $instance_name ] || [ -z $local_file ] || [ -z $remote_file ]
then
  echo "usage: scp-get <instance_name> <remote-file> <local-file>"
  exit 1
fi

scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@${instance_name}.aws.mine:${remote_file} ${local_file}
