#!/bin/sh

instance_name=$1

if [ -z $instance_name ]
then
  echo "usage: ssh <instance_name>"
  exit 1
fi

ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@${instance_name}.aws.mine
