#!/bin/sh

# CAUTION
# This script will only work with x.p.nifi.

instance_name=$1

usage="update-hostname <instance_name>"
if [ -z $instance_name ]
then
  echo $usage
  exit 1
fi

./ssh $instance_name "sudo hostname $instance_name.aws.mine" \
&& ./ssh $instance_name 'cat /opt/nifi/conf/nifi.properties.template |sed "s/REPLACE_WITH_HOSTNAME/$(hostname)/g" > /opt/nifi/conf/nifi.properties' \
&& ./ssh $instance_name 'cat /etc/ganglia/gmond.conf.template |sed "s/REPLACE_WITH_HOSTNAME/$(hostname)/g" > /etc/ganglia/gmond.conf' \
&& ./ssh $instance_name 'sudo service gmond restart'
