#!/bin/sh

# CAUTION
# This script will only work with x.p.nifi.

instance_name=$1
template_suffix=$2

usage="update-hostname <instance_name>"
if [ -z $instance_name ]
then
  echo $usage
  exit 1
fi


./ssh $instance_name "sudo hostname $instance_name.aws.mine" \
&& ./ssh $instance_name 'cat /opt/nifi/conf/nifi.properties.template.plain |sed "s/REPLACE_WITH_HOSTNAME/$(hostname)/g" |sed "s/REPLACE_WITH_CLUSTER_NAME/$(hostname |sed s/^[^.].//)/g" > /opt/nifi/conf/nifi.properties.plain' \
&& ./ssh $instance_name 'cat /opt/nifi/conf/nifi.properties.template.secure |sed "s/REPLACE_WITH_HOSTNAME/$(hostname)/g" |sed "s/REPLACE_WITH_CLUSTER_NAME/$(hostname |sed s/^[^.].//)/g" > /opt/nifi/conf/nifi.properties.secure' \
&& ./ssh $instance_name 'cat /etc/ganglia/gmond.conf.template |sed "s/REPLACE_WITH_HOSTNAME/$(hostname)/g" > /etc/ganglia/gmond.conf' \
&& ./ssh $instance_name 'sudo service gmond restart'
